library(plot3D)
data=read.csv("/home/poulami/Documents/Github/JournalInfluence/temp.csv")
print(data)
x =c(data$current)
z =c(data$change_of_influence)
y=c(data$history)
d<-data.frame(x,y,z)
#library(minpack.lm)
#b1<-min(y)
#a1<-max(y)-min(y)
plot(data$year,z,lwd=2,col="purple")
#lines(x,z)
model = nls(z~a*x+b*y,data= d)
print(confint(model))

new.data <- data.frame(x=seq(min(x),max(x)),len = 100)
print(model)
influence=predict(model)
year=data$year
#model<-nls(y~a*exp(-r*x)+b*exp(r*x))
print(cor(z,predict(model)))
print(confint(model))
#lines(new.data$x,new.data$z,predict(model,newdata = new.data))
lines(year,predict(model))

#lines(x, predict(model, list(x)), lwd=3, col="red")
#scatter3D(x = data$current, y = data$history,z = data$influence)
#print(predict(model))
#lines3D(x, y, z)
#lines3D(x,y ,predict(model))

